/* This file auto generated by Probe Parameter Editor,Don't change it manually */
#include "main.h"
/*#include "flash.h"*/
#include "modbus.h"
#include "string.h"
/*#include "stdio.h"
#include "cv.h"*/
uint8_t CheckUint16(uint16_t* input, uint16_t min, uint16_t max, uint16_t defaultv) 
{
	if (min <= (*input) && (*input) <= max)
	{
		return 0;
	}
	else
	{
		*input = defaultv;
		return 1;
	}
}
uint8_t CheckUint32(uint32_t* input, uint32_t min, uint32_t max, uint32_t defaultv) 
{
	if (min <= (*input) && (*input) <= max)
	{
		return 0;
	}
	else
	{
		*input = defaultv;
		return 1;
	}
}
#include "math.h"
#define FLOAT_MAX (3.4E8f)
#define FLOAT_MIN (-3.4E8f)

#define ALLOW_FP_ZERO 1
#define FORBID_FP_ZERO 0


uint8_t CheckFloat(void *input, float min, float max, uint8_t allow_fp_zero, float defaultv) 
{
	float CheckFloatInput;
	
	uint8_t *ptr = (uint8_t *)(&CheckFloatInput);
	uint8_t *in =  (uint8_t *)input;
	
	ptr[0] = in[0];
	ptr[1] = in[1];
	ptr[2] = in[2];
	ptr[3] = in[3];
	
	int FpRes = 0;
	FpRes = fpclassify(CheckFloatInput);
	if (FpRes == FP_NORMAL)
	{
		if (min < (CheckFloatInput) && (CheckFloatInput) < max) 
		{
			return 0;
		}
		else
		{
			in[0] = ((uint8_t *)(&defaultv))[0];
			in[1] = ((uint8_t *)(&defaultv))[1];
			in[2] = ((uint8_t *)(&defaultv))[2];
			in[3] = ((uint8_t *)(&defaultv))[3];
			return 1;
		}
	} 
	else if (FpRes == FP_ZERO)
	{
		if (allow_fp_zero == ALLOW_FP_ZERO)
		{
			return 0;
		}
		else
		{
			in[0] = ((uint8_t *)(&defaultv))[0];
			in[1] = ((uint8_t *)(&defaultv))[1];
			in[2] = ((uint8_t *)(&defaultv))[2];
			in[3] = ((uint8_t *)(&defaultv))[3];
			return 1;
		}
			
	}
	else
	{
		in[0] = ((uint8_t *)(&defaultv))[0];
		in[1] = ((uint8_t *)(&defaultv))[1];
		in[2] = ((uint8_t *)(&defaultv))[2];
		in[3] = ((uint8_t *)(&defaultv))[3];
		return 1;
	}

}
//system_status default value define begin
const uint16_t default_system_status_runStatus = 0;
const uint16_t default_system_status_commStatus = 0;
const uint16_t default_system_status_calibStatus = 0;
const uint16_t default_system_status_configStatus = 0;
const uint32_t default_system_status_productNum = 101;
const char default_system_status_deviceName[16] = "TOC-Power";
const char default_system_status_serial[16] = "240001";
const uint16_t default_system_status_newStructFlg = 0x2222;
const uint16_t default_system_status_measureTarget = 0;
//system_status default value define end

//comm_settings default value define begin
const uint16_t default_comm_settings_modbusAddr = 10;
const uint16_t default_comm_settings_modbusDatabits = 8;
const uint16_t default_comm_settings_modbusParity = 2;
const uint32_t default_comm_settings_modbusBaud = 9600;
//comm_settings default value define end

//measure_settings default value define begin
const uint16_t default_measure_settings_sampleCycle = 0;
const float default_measure_settings_measureRange = 0.0f;
const float default_measure_settings_measureRange2 = 0.0f;
const uint16_t default_measure_settings_command = 0;
//measure_settings default value define end

//calib_settings default value define begin
//calib_settings default value define end

//filter_settings default value define begin
//filter_settings default value define end

//measure_values default value define begin
//measure_values default value define end

//rsvd_param default value define begin
const float default_rsvd_param_IN_FAN_RATE = 5.0f;
const float default_rsvd_param_OUT_FAN_RATE = 5.0f;
const float default_rsvd_param_PID_P = 180.0f;
const float default_rsvd_param_PID_I = 0.6f;
const float default_rsvd_param_PID_D = 120.0f;
const float default_rsvd_param_setTemperature = 25.0f;
const float default_rsvd_param_tecPowerNow = 10.0f;
const float default_rsvd_param_tecBias = 0.001f;
const uint16_t default_rsvd_param_command = 0;
const uint16_t default_rsvd_param_LED1 = 0;
const uint16_t default_rsvd_param_LED2 = 0;
const uint16_t default_rsvd_param_LED3 = 0;
const uint16_t default_rsvd_param_LED4 = 0;
const uint16_t default_rsvd_param_tempStatus = 0;
const uint16_t default_rsvd_param_rsvd1 = 0;
//rsvd_param default value define end

void ParametarsInitByDefaultValue()
{
    //system_status power on parameters init begin
    system_status.runStatus = default_system_status_runStatus;
    system_status.commStatus = default_system_status_commStatus;
    system_status.calibStatus = default_system_status_calibStatus;
    system_status.configStatus = default_system_status_configStatus;
    system_status.productNum = default_system_status_productNum;
    strcpy(system_status.deviceName, default_system_status_deviceName);
    strcpy(system_status.serial, default_system_status_serial);
    system_status.newStructFlg = default_system_status_newStructFlg;
    system_status.measureTarget = default_system_status_measureTarget;
    //system_status power on parameters init end

    //comm_settings power on parameters init begin
    comm_settings.modbusAddr = default_comm_settings_modbusAddr;
    comm_settings.modbusDatabits = default_comm_settings_modbusDatabits;
    comm_settings.modbusParity = default_comm_settings_modbusParity;
    comm_settings.modbusBaud = default_comm_settings_modbusBaud;
    //comm_settings power on parameters init end

    //measure_settings power on parameters init begin
    measure_settings.sampleCycle = default_measure_settings_sampleCycle;
    measure_settings.measureRange = default_measure_settings_measureRange;
    measure_settings.measureRange2 = default_measure_settings_measureRange2;
    measure_settings.command = default_measure_settings_command;
    //measure_settings power on parameters init end

    //calib_settings power on parameters init begin
    //calib_settings power on parameters init end

    //filter_settings power on parameters init begin
    //filter_settings power on parameters init end

    //measure_values power on parameters init begin
    //measure_values power on parameters init end

    //rsvd_param power on parameters init begin
    rsvd_param.IN_FAN_RATE = default_rsvd_param_IN_FAN_RATE;
    rsvd_param.OUT_FAN_RATE = default_rsvd_param_OUT_FAN_RATE;
    rsvd_param.PID_P = default_rsvd_param_PID_P;
    rsvd_param.PID_I = default_rsvd_param_PID_I;
    rsvd_param.PID_D = default_rsvd_param_PID_D;
    rsvd_param.setTemperature = default_rsvd_param_setTemperature;
    rsvd_param.tecPowerNow = default_rsvd_param_tecPowerNow;
    rsvd_param.tecBias = default_rsvd_param_tecBias;
    rsvd_param.command = default_rsvd_param_command;
    rsvd_param.LED1 = default_rsvd_param_LED1;
    rsvd_param.LED2 = default_rsvd_param_LED2;
    rsvd_param.LED3 = default_rsvd_param_LED3;
    rsvd_param.LED4 = default_rsvd_param_LED4;
    rsvd_param.tempStatus = default_rsvd_param_tempStatus;
    rsvd_param.rsvd1 = default_rsvd_param_rsvd1;
    //rsvd_param power on parameters init end

}
uint8_t CheckParamyDefaultSetting()
{
	uint8_t update_flg = 0;
	{
        //system_status check parameters begin
       update_flg += CheckUint16(&system_status.measureTarget, 0, 100, default_system_status_measureTarget);
        //system_status check parameters end

        //comm_settings check parameters begin
       update_flg += CheckUint16(&comm_settings.modbusAddr, 1, 250, default_comm_settings_modbusAddr);
       update_flg += CheckUint16(&comm_settings.modbusDatabits, 8, 9, default_comm_settings_modbusDatabits);
       update_flg += CheckUint16(&comm_settings.modbusParity, 0, 2, default_comm_settings_modbusParity);
       update_flg += CheckUint32(&comm_settings.modbusBaud, 1200, 115200, default_comm_settings_modbusBaud);
        //comm_settings check parameters end

        //measure_settings check parameters begin
       update_flg += CheckUint16(&measure_settings.sampleCycle, 0, 1000, default_measure_settings_sampleCycle);
       update_flg += CheckFloat(&measure_settings.measureRange, 0.0f, 1000.0f, FORBID_FP_ZERO, default_measure_settings_measureRange);
       update_flg += CheckFloat(&measure_settings.measureRange2, 0.0f, 1000.0f, FORBID_FP_ZERO, default_measure_settings_measureRange2);
       update_flg += CheckUint16(&measure_settings.command, 0, 1000, default_measure_settings_command);
        //measure_settings check parameters end

        //calib_settings check parameters begin
        //calib_settings check parameters end

        //filter_settings check parameters begin
        //filter_settings check parameters end

        //measure_values check parameters begin
        //measure_values check parameters end

        //rsvd_param check parameters begin
       update_flg += CheckFloat(&rsvd_param.IN_FAN_RATE, 0.01f, 100.0f, FORBID_FP_ZERO, default_rsvd_param_IN_FAN_RATE);
       update_flg += CheckFloat(&rsvd_param.OUT_FAN_RATE, 0.01f, 100.0f, FORBID_FP_ZERO, default_rsvd_param_OUT_FAN_RATE);
       update_flg += CheckFloat(&rsvd_param.PID_P, -10000.0f, 10000.0f, FORBID_FP_ZERO, default_rsvd_param_PID_P);
       update_flg += CheckFloat(&rsvd_param.PID_I, -10000.0f, 10000.0f, FORBID_FP_ZERO, default_rsvd_param_PID_I);
       update_flg += CheckFloat(&rsvd_param.PID_D, -10000.0f, 10000.0f, FORBID_FP_ZERO, default_rsvd_param_PID_D);
       update_flg += CheckFloat(&rsvd_param.setTemperature, 5.0f, 50.0f, FORBID_FP_ZERO, default_rsvd_param_setTemperature);
       update_flg += CheckFloat(&rsvd_param.tecPowerNow, -100.0f, 100.0f, FORBID_FP_ZERO, default_rsvd_param_tecPowerNow);
       update_flg += CheckFloat(&rsvd_param.tecBias, -200.0f, 200.0f, FORBID_FP_ZERO, default_rsvd_param_tecBias);
       update_flg += CheckUint16(&rsvd_param.command, 0, 1000, default_rsvd_param_command);
       update_flg += CheckUint16(&rsvd_param.LED1, 0, 1000, default_rsvd_param_LED1);
       update_flg += CheckUint16(&rsvd_param.LED2, 0, 1000, default_rsvd_param_LED2);
       update_flg += CheckUint16(&rsvd_param.LED3, 0, 1000, default_rsvd_param_LED3);
       update_flg += CheckUint16(&rsvd_param.LED4, 0, 1000, default_rsvd_param_LED4);
       update_flg += CheckUint16(&rsvd_param.tempStatus, 0, 1000, default_rsvd_param_tempStatus);
       update_flg += CheckUint16(&rsvd_param.rsvd1, 0, 1000, default_rsvd_param_rsvd1);
        //rsvd_param check parameters end

	}
	return update_flg;
}
