/* This file auto generated by Probe Parameter Editor,Don't change it manually */
#include "main.h"
#include "flash.h"
#include "modbus.h"
#include "string.h"
#include "stdio.h"
#include "cv.h"
uint8_t CheckUint16(uint16_t* input, uint16_t min, uint16_t max, uint16_t defaultv) 
{
	if (min <= (*input) && (*input) <= max)
	{
		return 0;
	}
	else
	{
		*input = defaultv;
		return 1;
	}
}
uint8_t CheckUint32(uint32_t* input, uint32_t min, uint32_t max, uint32_t defaultv) 
{
	if (min <= (*input) && (*input) <= max)
	{
		return 0;
	}
	else
	{
		*input = defaultv;
		return 1;
	}
}
#include "math.h"
#define FLOAT_MAX (3.4E8f)
#define FLOAT_MIN (-3.4E8f)

#define ALLOW_FP_ZERO 1
#define FORBID_FP_ZERO 0


uint8_t CheckFloat(void *input, float min, float max, uint8_t allow_fp_zero, float defaultv) 
{
	float CheckFloatInput;
	
	uint8_t *ptr = (uint8_t *)(&CheckFloatInput);
	uint8_t *in =  (uint8_t *)input;
	
	ptr[0] = in[0];
	ptr[1] = in[1];
	ptr[2] = in[2];
	ptr[3] = in[3];
	
	int FpRes = 0;
	FpRes = fpclassify(CheckFloatInput);
	if (FpRes == FP_NORMAL)
	{
		if (min < (CheckFloatInput) && (CheckFloatInput) < max) 
		{
			return 0;
		}
		else
		{
			in[0] = ((uint8_t *)(&defaultv))[0];
			in[1] = ((uint8_t *)(&defaultv))[1];
			in[2] = ((uint8_t *)(&defaultv))[2];
			in[3] = ((uint8_t *)(&defaultv))[3];
			return 1;
		}
	} 
	else if (FpRes == FP_ZERO)
	{
		if (allow_fp_zero == ALLOW_FP_ZERO)
		{
			return 0;
		}
		else
		{
			in[0] = ((uint8_t *)(&defaultv))[0];
			in[1] = ((uint8_t *)(&defaultv))[1];
			in[2] = ((uint8_t *)(&defaultv))[2];
			in[3] = ((uint8_t *)(&defaultv))[3];
			return 1;
		}
			
	}
	else
	{
		in[0] = ((uint8_t *)(&defaultv))[0];
		in[1] = ((uint8_t *)(&defaultv))[1];
		in[2] = ((uint8_t *)(&defaultv))[2];
		in[3] = ((uint8_t *)(&defaultv))[3];
		return 1;
	}

}
//system_status default value define begin
const uint16_t default_system_status_runStatus = 0;
const uint16_t default_system_status_commStatus = 0;
const uint16_t default_system_status_calibStatus = 0;
const uint16_t default_system_status_configStatus = 0;
const uint32_t default_system_status_productNum = 101;
const char default_system_status_deviceName[16] = "TOC-Power";
const char default_system_status_serial[16] = "240001";
const uint16_t default_system_status_newStructFlg = 0x2222;
const uint16_t default_system_status_measureTarget = 0;
//system_status default value define end

//comm_settings default value define begin
const uint16_t default_comm_settings_modbusAddr = 10;
const uint16_t default_comm_settings_modbusDatabits = 8;
const uint16_t default_comm_settings_modbusParity = 2;
const uint32_t default_comm_settings_modbusBaud = 9600;
//comm_settings default value define end

//measure_settings default value define begin
const uint16_t default_measure_settings_sampleCycle = 2;
const float default_measure_settings_measureRange = 100.0f;
const float default_measure_settings_measureRange2 = 100.0f;
const uint16_t default_measure_settings_command = 0;
//measure_settings default value define end

//calib_settings default value define begin
//calib_settings default value define end

//filter_settings default value define begin
//filter_settings default value define end

//measure_values default value define begin
//measure_values default value define end

//rsvd_param default value define begin
const float default_rsvd_param_flowRateNow = 5.0f;
const float default_rsvd_param_flowRateAve = 5.0f;
const float default_rsvd_param_aveNum = 5.0f;
const float default_rsvd_param_flowRateSet = 5.0f;
const float default_rsvd_param_valveOpening = 30.0f;
const uint16_t default_rsvd_param_manualMode = 1;
const uint16_t default_rsvd_param_modbusCmd2 = 0;
//rsvd_param default value define end

void ParametarsInitByDefaultValue()
{
    //system_status power on parameters init begin
    system_status.runStatus = default_system_status_runStatus;
    system_status.commStatus = default_system_status_commStatus;
    system_status.calibStatus = default_system_status_calibStatus;
    system_status.configStatus = default_system_status_configStatus;
    system_status.productNum = default_system_status_productNum;
    strcpy(system_status.deviceName, default_system_status_deviceName);
    strcpy(system_status.serial, default_system_status_serial);
    system_status.newStructFlg = default_system_status_newStructFlg;
    system_status.measureTarget = default_system_status_measureTarget;
    //system_status power on parameters init end

    //comm_settings power on parameters init begin
    comm_settings.modbusAddr = default_comm_settings_modbusAddr;
    comm_settings.modbusDatabits = default_comm_settings_modbusDatabits;
    comm_settings.modbusParity = default_comm_settings_modbusParity;
    comm_settings.modbusBaud = default_comm_settings_modbusBaud;
    //comm_settings power on parameters init end

    //measure_settings power on parameters init begin
    measure_settings.sampleCycle = default_measure_settings_sampleCycle;
    measure_settings.measureRange = default_measure_settings_measureRange;
    measure_settings.measureRange2 = default_measure_settings_measureRange2;
    measure_settings.command = default_measure_settings_command;
    //measure_settings power on parameters init end

    //calib_settings power on parameters init begin
    //calib_settings power on parameters init end

    //filter_settings power on parameters init begin
    //filter_settings power on parameters init end

    //measure_values power on parameters init begin
    //measure_values power on parameters init end

    //rsvd_param power on parameters init begin
    rsvd_param.flowRateNow = default_rsvd_param_flowRateNow;
    rsvd_param.flowRateAve = default_rsvd_param_flowRateAve;
    rsvd_param.aveNum = default_rsvd_param_aveNum;
    rsvd_param.flowRateSet = default_rsvd_param_flowRateSet;
    rsvd_param.valveOpening = default_rsvd_param_valveOpening;
    rsvd_param.manualMode = default_rsvd_param_manualMode;
    rsvd_param.modbusCmd2 = default_rsvd_param_modbusCmd2;
    //rsvd_param power on parameters init end

}
uint8_t CheckParamyDefaultSetting()
{
	uint8_t update_flg = 0;
	{
        //system_status check parameters begin
       update_flg += CheckUint16(&system_status.measureTarget, 0, 100, default_system_status_measureTarget);
        //system_status check parameters end

        //comm_settings check parameters begin
       update_flg += CheckUint16(&comm_settings.modbusAddr, 1, 250, default_comm_settings_modbusAddr);
       update_flg += CheckUint16(&comm_settings.modbusDatabits, 8, 9, default_comm_settings_modbusDatabits);
       update_flg += CheckUint16(&comm_settings.modbusParity, 0, 2, default_comm_settings_modbusParity);
       update_flg += CheckUint32(&comm_settings.modbusBaud, 1200, 115200, default_comm_settings_modbusBaud);
        //comm_settings check parameters end

        //measure_settings check parameters begin
       update_flg += CheckUint16(&measure_settings.sampleCycle, 0, 1000, default_measure_settings_sampleCycle);
       update_flg += CheckFloat(&measure_settings.measureRange, 0.0f, 1000.0f, FORBID_FP_ZERO, default_measure_settings_measureRange);
       update_flg += CheckFloat(&measure_settings.measureRange2, 0.0f, 1000.0f, FORBID_FP_ZERO, default_measure_settings_measureRange2);
       update_flg += CheckUint16(&measure_settings.command, 0, 1000, default_measure_settings_command);
        //measure_settings check parameters end

        //calib_settings check parameters begin
        //calib_settings check parameters end

        //filter_settings check parameters begin
        //filter_settings check parameters end

        //measure_values check parameters begin
        //measure_values check parameters end

        //rsvd_param check parameters begin
       update_flg += CheckFloat(&rsvd_param.flowRateNow, 0.01f, 30.0f, FORBID_FP_ZERO, default_rsvd_param_flowRateNow);
       update_flg += CheckFloat(&rsvd_param.flowRateAve, 0.01f, 30.0f, FORBID_FP_ZERO, default_rsvd_param_flowRateAve);
       update_flg += CheckFloat(&rsvd_param.aveNum, 0.01f, 100.0f, FORBID_FP_ZERO, default_rsvd_param_aveNum);
       update_flg += CheckFloat(&rsvd_param.flowRateSet, 0.01f, 30.0f, FORBID_FP_ZERO, default_rsvd_param_flowRateSet);
       update_flg += CheckFloat(&rsvd_param.valveOpening, 0.01f, 100.0f, FORBID_FP_ZERO, default_rsvd_param_valveOpening);
       update_flg += CheckUint16(&rsvd_param.manualMode, 0, 5, default_rsvd_param_manualMode);
       update_flg += CheckUint16(&rsvd_param.modbusCmd2, 0, 1000, default_rsvd_param_modbusCmd2);
        //rsvd_param check parameters end

	}
	return update_flg;
}
