/* This file auto generated by Probe Parameter Editor,Don't change it manually */
/* Define to prevent recursive inclusion --------------------------------------*/
#ifndef __REGMAP_H
#define __REGMAP_H
/* Includes -------------------------------------------------------------------*/
#include "stm32l4xx_hal.h"
#include "stm32l4xx.h"
#include "cv.h"
/* Exported_Types -------------------------------------------------------------*/
/*2 byte aligned*/
#pragma pack(2)
//SYS_STATUS_T Define Begin
typedef struct // 41001
{
   uint16_t runStatus;  //41001
   uint16_t commStatus;  //41002
   uint16_t calibStatus;  //41003
   uint16_t configStatus;  //41004
   uint32_t productNum;  //41005
   char deviceName[16];  //41007
   char serial[16];  //41015
   char hardwareVer[16];  //41023
   char softwareVer[16];  //41031
   uint16_t newStructFlg;  //41039
   uint16_t measureTarget;  //41040
   uint16_t reserved[12];  //
}SYS_STATUS_T;
//SYS_STATUS_T Define End

//COMM_SETTINGS_T Define Begin
typedef struct // 42001
{
   uint16_t modbusAddr;  //42001
   uint16_t modbusDatabits;  //42002
   uint16_t modbusParity;  //42003
   uint32_t modbusBaud;  //42004
   uint16_t reserved[47];  //
}COMM_SETTINGS_T;
//COMM_SETTINGS_T Define End

//MEASURE_SETTINGS_T Define Begin
typedef struct // 43001
{
   uint16_t sampleCycle;  //43001
   float measureRange;  //43002
   float measureRange2;  //43004
   uint16_t command;  //43006
   uint16_t reserved[46];  //
}MEASURE_SETTINGS_T;
//MEASURE_SETTINGS_T Define End

//CALIB_SETTINGS_T Define Begin
typedef struct // 44001
{
   uint16_t reserved[52];  //
}CALIB_SETTINGS_T;
//CALIB_SETTINGS_T Define End

//FILTER_SETTINGS_T Define Begin
typedef struct // 45001
{
   uint16_t reserved[52];  //
}FILTER_SETTINGS_T;
//FILTER_SETTINGS_T Define End

//MEASURE_VALUES_T Define Begin
typedef struct // 46001
{
   float tecPowerNow;  //46001
   float temperature1;  //46003
   float temperature2;  //46005
   uint16_t reserved[46];  //
}MEASURE_VALUES_T;
//MEASURE_VALUES_T Define End

//RSVD_PARAM_T Define Begin
typedef struct // 48001
{
   float flowRateVoltageAve;  //48001
   float flowRateAve;  //48003
   float filterFactor;  //48005
   float flowRateSet;  //48007
   float valveOpening;  //48009
   uint16_t manualMode;  //48011
   uint16_t modbusCmd2;  //48012
   float lowFlow;  //48013
   float highFlow;  //48015
   float lowFlowVoltage;  //48017
   float highFlowVoltage;  //48019
   float PID_P;  //48021
   float PID_I;  //48023
   float PID_D;  //48025
   uint16_t reserved[26];  //
}RSVD_PARAM_T;
//RSVD_PARAM_T Define End

#pragma pack()
#endif
